### ISSUE TITLE
Make sections collapsible 

### ISSUE THREAD

**Issue by mknepprath** [brianlovin/security-checklist#10]
My wife mentioned that it doesn't necessarily "read" like a checklist right now - perhaps the sections should start out in a collapsed state that visitors can expand. Perhaps a chevron on the right to indicate open/closed state (not pictured)...

<img width="732" alt="screen shot 2019-01-13 at 4 14 06 pm" src="https://user-images.githubusercontent.com/1000280/51091275-43916200-174e-11e9-8320-e3953e209b9b.png">

They could default closed, or maybe default closed - except for the first unchecked list item? Just throwing out what's popping into my head here, lmk what you think.

**Comment by brianlovin** [comment]
This is a good point. I had a prototype earlier of collapsing things when you checked them as complete, but it felt a bit jumpy. I think an explicit action to collapse will be useful.

I'm worried that having things collapsed by default might mean a lot of people miss some of the resources and apps because they don't know to expand. Maybe open by default, but ability to collapse/collapse all in a click?

**Comment by brianlovin** [comment]
I hope I knocked this out how you'd pictured in #14 @mknepprath :)

**Comment by mknepprath** [comment]
@brianlovin Yep, that looks great!
